# Generated by Django 5.0.6 on 2024-05-28 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("hospital", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="hospital",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="hospital.hospital",
            ),
        ),
    ]
