# Generated by Django 5.0.6 on 2024-09-12 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(default=1, upload_to="lab/profile-images"),
            preserve_default=False,
        ),
    ]
