# Generated by Django 5.0.6 on 2024-05-28 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_hospital"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="hospital",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="core.hospital",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_hospital_admin",
            field=models.BooleanField(default=False),
        ),
    ]
