# Generated by Django 5.0.6 on 2024-07-15 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0002_remove_resultimagedata_image_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="resultimagedata",
            old_name="image_urls",
            new_name="image",
        ),
    ]
