# Generated by Django 5.0.6 on 2024-05-24 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0002_alter_bloodtest_id_alter_patient_id_alter_result_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="BloodTestImageData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="lab/images")),
                (
                    "blood_test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="lab.bloodtest",
                    ),
                ),
            ],
        ),
    ]
