# Generated by Django 5.0.6 on 2024-09-03 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0003_rename_image_urls_resultimagedata_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="LabResultDetection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("detection_type", models.CharField(max_length=50)),
                ("detection_value", models.IntegerField()),
                (
                    "result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detections",
                        to="lab.result",
                    ),
                ),
            ],
        ),
    ]
