# Generated by Django 5.0.6 on 2024-05-24 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0003_bloodtestimagedata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bloodtestimagedata",
            name="image",
            field=models.ImageField(upload_to="lab/data-images"),
        ),
    ]
