# Generated by Django 5.0.6 on 2024-05-24 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0004_alter_bloodtestimagedata_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResultImageData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="lab/result-images")),
                (
                    "result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result_images",
                        to="lab.result",
                    ),
                ),
            ],
        ),
    ]
